feature: добавление новой функциональности:
ekip-s/java-shareit pull request #1
Opened 2022-10-16 16:12 UTC by ekip-s

- работа с пользователями и вещами;

2022-10-18 15:23 UTC, Fleaman777 requested changes

2022-10-18 15:23 UTC, Fleaman777 commented on pom.xml
> -
а это так и надо было, почистить немного пом файл ?

2022-10-18 15:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    }
не совсем обязательный хэндлер, т.к. спринг, в случае, если в приложении вылетит какой-нибудь эксепшен, сам вернет 500 код

2022-10-18 15:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<Item> get(@RequestHeader("X-Sharer-User-Id") long userId) {
X-Sharer-User-Id - можно было бы вынести в константу и использовать ее в разных методах

2022-10-18 15:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                "userId=" + userId + ", itemId=" + itemId);
в логе только 1 плейсхолдер {}, но передается 2 параметра, 
различные кодстайл чекеры(например sonar qube)? не пропустили бы такое

2022-10-18 15:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotNull(message = "Ошибка валидации: не указан available")
молодец, что используешь валидацию через аннотацию, так код лучше воспринимается

2022-10-18 15:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    }
попробуй этот foreach сделать через stream, а что бы было чуть легче,
часть логики, например  
i.stream()
                        .filter(g -> Objects.equals(itemId, g.getId()))
                        .findAny();
можно было бы вынестли в отдельный вспомогательный метод.

со стримом код выглядел бы поаккуратней

2022-10-18 15:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        }
а нужна ли в этом методу переменная i, может просто сразу возвращать резуьтаты, без присваивания результата к i

2022-10-18 15:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        }
здесь тоже можешь попробовать часть логики переделать на стрим

2022-10-18 15:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private void userExistenceCheck(long id) {
отличное решение, с вынесением общей логики валидации в отдельный метод

2022-10-18 15:51 UTC, ekip-s commented on pom.xml
> -
там чет само понадобавлялось, из-за этого сборка не проходила. 
Почистил - прошла;

2022-10-18 18:12 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    }
если он натыкается на хибенейт валидатор отдает 400. Удаляю, сразу + 5 ошибок; В ним все ок

2022-10-18 18:15 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<Item> get(@RequestHeader("X-Sharer-User-Id") long userId) {
согласен - поправил;

2022-10-18 18:24 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                "userId=" + userId + ", itemId=" + itemId);
понял ошибку прочитав доку;

2022-10-18 18:25 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                "userId=" + userId + ", itemId=" + itemId);
но параметр там один - запятая в кавычках; Но это лажа, я понял)

2022-10-18 18:26 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotNull(message = "Ошибка валидации: не указан available")
так просто проще) 
лень она такая

2022-10-18 19:24 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    }
не знаю насколько это правильно, но мы добавили вам стрим в стрим, чтобы когда ..

2022-10-18 19:27 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        }
тут вообще почти все удалил;

2022-10-18 19:37 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        }
здесь вроде все в стриме, но я упростил написание, вынеся одну проверку в отдельный фильтр;

2022-10-19 11:43 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    }
окей, поинт засчитан)

2022-10-19 16:50 UTC, Fleaman777 requested changes

2022-10-19 16:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static final String sharerUserId = "X-Sharer-User-Id";
поскольку это константа, то ее надо называть в верхнем регистре

2022-10-19 16:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +
супер, совсем другой вид

2022-10-19 16:50 UTC, Fleaman777 commented on pom.xml
> -
вообще это как раз всякие кодстайл чекеры, проверяют отступы, лишние импорты, покрытие кода и пр., 
в целом ничего криминального в них нет, и скорее всего добавлены специально, так что я бы не стал просто так их удалять, без подтверждения, что они не нужны 

 билд падал из-за ошибок, чаще всего где-то не проставил пробелы или не удалил ненужные импорты: 
 https://github.com/ekip-s/java-shareit/actions/runs/3260100716/jobs/5353410875
 
 большинство, фиксится довольно просто, 
 во всех новых классах нажимаешь Ctrl+Alt+L и Ctrl+Alt+O 
 
 возможно некоторые придется пофиксить вручную, если будут вопросы, пиши

2022-10-19 19:30 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static final String sharerUserId = "X-Sharer-User-Id";
согласен, туплю.

2022-10-19 19:32 UTC, ekip-s commented on pom.xml
> -
Короче я играл с плагинами и думал что кто-то из них нагадил мне в pom, а это так задумано оказалось. 

Вернул все как было, все проправил - не ругается. (долго не мог понять чего он хочет, а это был пробел после if))

2022-10-20 07:03 UTC, Fleaman777 commented on pom.xml
> -
оо да, тоже на работе бывает подобная тема, на дурацкий пробел можно больше времени потратить, чем на задачу))

2022-11-01 09:53 UTC, merged