feat: добавлени базы данных и бронирования
ekip-s/java-shareit pull request #2
Opened 2022-11-06 15:57 UTC by ekip-s

2022-11-07 19:30 UTC, Fleaman777 requested changes

2022-11-07 19:30 UTC, Fleaman777 commented on pom.xml
> +			<groupId>com.h2database</groupId>
почему решил использовать h2 database? а не postgres, как указано в задании 
в этом проекте должна использоваться именно постгрес

2022-11-07 19:30 UTC, Fleaman777 commented on pom.xml
> +			<artifactId>spring-boot-starter-jdbc</artifactId>
скорее всего, эта депенденси не нужна, т.к. все необходимое есть в более объемной spring-data-jpa

2022-11-07 19:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    BookingService bookingService;
поле должно быть private

2022-11-07 19:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/RequestParameters.java
> +public enum RequestParameters {
чуть правильней будет, перенести этот енам в пакет model

2022-11-07 19:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/EnumConverter.java
> +public class EnumConverter implements Converter<String, RequestParameters> {
этот конвертер можно в пакет сервис перенести

2022-11-07 19:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceJPA.java
> +    EntityManager entityManager;
здесь и в др аналагичных местах, поля должны быть private

2022-11-07 19:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceJPA.java
> +            Item item = booking.getItem();
можно не создавать отдельную локальную перменную item, т.к. она используется только в 1 месте, в котором можно сразу сделать booking.getItem()

2022-11-07 19:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceJPA.java
> +        checkUserId(booking.getBooker().getId(), userId, booking.getItem().getOwner().getId());
а вот здесь booking.getItem().getOwner().getId() - вынести в локальную перменную, что бы не дублировать получение айдишника

2022-11-07 19:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceJPA.java
> +        LocalDateTime nowDT = LocalDateTime. now();
а здесь здорово вынес текущую дату в отдельную переменную

2022-11-07 19:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceJPA.java
> +        }
для улучшения восприятия этого длинного метода, логику в case можно вынести во вспомогательные методы с подходящими названиями, в таком случае: 
при беглом просмотре кода из названия будет понтяно, что именно происходит в том или ином case, а если нужно будет более детально понять, что именно происходит, можно просто будет перести в конкретный вспомогательный метод

2022-11-07 19:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceJPA.java
> +    private void checkEntity(long userId, Optional<Item> optionalItem, BookingDto booking) {
хороший валидационный метод, 
неплохо воспринимается + понятно в чем именно не проходит валидация

2022-11-07 19:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceJPA.java
> +            throw new ConflictException("Товар сейчас не доступер, выберите другой");
опечатка "доступен"

2022-11-07 19:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceJPA.java
> +        return itemDtoList;
хороший метод для того, что бы сделать его через стрим

2022-11-07 19:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceJPA.java
> +    }
этот метод тоже можно было бы выполнить через стрим, выглядело бы поаккуратней

2022-11-07 19:30 UTC, Fleaman777 commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS сomment;
понимаю для чего это сейчас сделано, 
но в будущем, конечно так не надо будет делать,  
иначе весь смысл базы данных, пропалет)

2022-11-08 15:59 UTC, ekip-s commented on pom.xml
> +			<groupId>com.h2database</groupId>
блин как-то по автоматом сделал. Ща поправим.

2022-11-08 16:03 UTC, ekip-s commented on pom.xml
> +			<artifactId>spring-boot-starter-jdbc</artifactId>
спс.

2022-11-08 18:22 UTC, ekip-s commented on pom.xml
> +			<groupId>com.h2database</groupId>
есть

2022-11-08 18:22 UTC, ekip-s commented on pom.xml
> +			<artifactId>spring-boot-starter-jdbc</artifactId>
готово

2022-11-08 18:23 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    BookingService bookingService;
пропустил, поправил.

2022-11-08 18:25 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/booking/controller/RequestParameters.java
> +public enum RequestParameters {
исходил из того, что я его юзаю в контроллере для валидации - поэтому здесь поместил. Поправиль;

2022-11-08 18:26 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/booking/controller/EnumConverter.java
> +public class EnumConverter implements Converter<String, RequestParameters> {
а это я поставил в связке с enum к которому он прикреплен

2022-11-08 18:27 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceJPA.java
> +    private void checkEntity(long userId, Optional<Item> optionalItem, BookingDto booking) {
круть

2022-11-08 18:29 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceJPA.java
> +            throw new ConflictException("Товар сейчас не доступер, выберите другой");
бывает

2022-11-08 18:29 UTC, ekip-s commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS сomment;
зато место экономим в БД))

2022-11-08 18:47 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceJPA.java
> +        return itemDtoList;
Чет пропустил этот момент, готово;

2022-11-08 18:47 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceJPA.java
> +    }
готово

2022-11-20 21:13 UTC, merged