feature: добавил запросы выещей, опцию ответа на запроси и тесты;
ekip-s/java-shareit pull request #3
Opened 2022-12-04 20:18 UTC by ekip-s

2022-12-06 15:18 UTC, Fleaman777 requested changes

2022-12-06 15:18 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceJPA.java
> +                        " ORDER BY b.start DESC");
логика с запросами к БД должна находится в слое репозиторий, 
в сервисе только вызовы методов из репозитория 

относится ко всем похожим местам

2022-12-06 15:18 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceJPA.java
> +        Pageable page = PageRequest.of(from, size, Sort.by("start").descending());
получение объектра page и расчет from можно было бы вынести в отдельный метод,

2022-12-06 15:18 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    }
хороший метод, делает все необходимые общие вещи перед запуском теста

2022-12-06 15:18 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +                .header("X-Sharer-User-Id", 1)
в тесте X-Sharer-User-Id тоже можно было бы вынести в константу

2022-12-06 15:18 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryJPATest.java
> +                new User(1L), PageRequest.of(0, 2));
объявление юзеров (new User(1L), PageRequest.of(0, 2), и др) 
похоже от метода к методу, можно вынести этот константу

2022-12-06 15:18 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryJPATest.java
> +    @Sql({"/test-schema.sql", "/test-data.sql"})
посмотри, 
можно ли эту аннотацию вынести на уровень класса, что бы не дублировать ее над каждым методом

2022-12-06 15:18 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceJPATest.java
> +    void getBookings() {
тест методы лучше называть не так, как они называются в основных кдассах приложения, что бы потом проще было искать по проекту 

самое простое другое название тест метода, добавить test 
testGetBookings 
или лучше добавлять при каких условиях выполняется тест
testGetBookingsIf.....

относится ко всем похожим местам

2022-12-06 15:18 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +    void get_items_list_page() throws Exception {
можно и в обычном камелКейс стиле называть)

2022-12-06 15:18 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceJPATest.java
> +    ItemRequest itemRequest;
в тестах тоже принято придерживаться инкапсуляции

2022-12-06 15:18 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceJPATest.java
> +}
общие объекты которые используются в методах, тоже можно было бы вынести в константы

2022-12-06 16:02 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceJPA.java
> +                        " ORDER BY b.start DESC");
Привет. 
Такая лажа только здесь. Поправил. Убрал в репозитарий, что уже есть в пакете;

2022-12-06 16:39 UTC, ekip-s commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceJPA.java
> +        Pageable page = PageRequest.of(from, size, Sort.by("start").descending());
from вынес в метод валидации, что выше; 
А page в отдельный метод;

2022-12-06 16:46 UTC, ekip-s commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +                .header("X-Sharer-User-Id", 1)
логично, сделал;

2022-12-06 16:58 UTC, ekip-s commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryJPATest.java
> +                new User(1L), PageRequest.of(0, 2));
убрал;

2022-12-06 18:49 UTC, ekip-s commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceJPATest.java
> +    void getBookings() {
сделал

2022-12-06 18:49 UTC, ekip-s commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +    void get_items_list_page() throws Exception {
случайно, поправил

2022-12-06 18:49 UTC, ekip-s commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceJPATest.java
> +    ItemRequest itemRequest;
пропустил

2022-12-06 18:50 UTC, ekip-s commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceJPATest.java
> +}
Сделал, где это актуально, конкретно выделенный момент один раз используется.

2022-12-07 18:06 UTC, Fleaman777 approved these changes

2022-12-11 18:17 UTC, merged