feature: добавление базы данных и разделение приложения на модули V00.01
ekip-s/java-shareit pull request #4
Opened 2022-12-15 05:41 UTC by ekip-s

2022-12-15 19:23 UTC, Fleaman777 requested changes

2022-12-15 19:23 UTC, Fleaman777 commented on docker-compose.yml
> +    image: postgres:13.7-alpine
хорошо, что указываешь конкретную версию имеджа, а не просто latest,
так безопасней, т.к. меньше шансов нарваться на версию базового имеджа, с которым текущая версия приложения не будет работать,

то же относится и к Dockerfile

2022-12-15 19:23 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/booking/BookingController.java
> +    private void idCheck(long id) {
название метода должно называться с глагола

2022-12-15 19:23 UTC, Fleaman777 commented on server/src/main/java/ru/practicum/exception/ErrorHandlerUser.java
> +        System.out.println("Jib,rf 4");
если нужно что-то залогировать, лучше использовать логгер, 
удобней, эффективней, больше возможнойстей

2022-12-15 19:23 UTC, Fleaman777 commented on server/src/main/resources/application.properties
> +spring.datasource.username=root
сейчас получается, что значения переменных окружения, используются те, которые указаны в application.properties, а не те, которые в docker-compose

например в application.properties ,
можно использовать такую конструкцию: spring.datasource.username=${POSTGRES_USER:root}
она означает, что если, в докер-компосе не просетать переменную POSTGRES_USER, то будет использоваться дефлотное значение root

2022-12-15 20:07 UTC, ekip-s commented on gateway/src/main/java/ru/practicum/booking/BookingController.java
> +    private void idCheck(long id) {
поменял

2022-12-15 20:10 UTC, ekip-s commented on server/src/main/java/ru/practicum/exception/ErrorHandlerUser.java
> +        System.out.println("Jib,rf 4");
это да, но я под утро делал, уже не соображал))

2022-12-15 20:13 UTC, ekip-s commented on server/src/main/resources/application.properties
> +spring.datasource.username=root
я когда тестил на локальной безе - забыл вернуть

2022-12-16 16:13 UTC, Fleaman777 approved these changes

2022-12-26 16:46 UTC, merged